ALTER TABLE t_p28211681_photo_secure_web.portfolio_reviews
  ADD COLUMN IF NOT EXISTS client_id BIGINT,
  ADD COLUMN IF NOT EXISTS client_phone VARCHAR(50),
  ADD COLUMN IF NOT EXISTS client_email VARCHAR(255),
  ADD COLUMN IF NOT EXISTS gallery_code VARCHAR(16),
  ADD COLUMN IF NOT EXISTS thanked BOOLEAN NOT NULL DEFAULT FALSE;